### ISSUE TITLE
costumes not showing ingame

### ISSUE THREAD

**Issue by julisnivy** [manaphoenix/IsaacTemplates#18]
I can't manage to get character costumes working

The step 4 in the CharacterCostume.html says "Apply the costume in the main.lua file" but I don't really understand what I have to modify in main.lua. I think that might be the problem.

**Comment by julisnivy** [comment]
nevermind I found out, It was something related to the animation tool. Thank you so much for this template!

**Comment by manaphoenix** [comment]
Glad it helped you, and I fixed that typo, never should you need to open Main.lua.
