### ISSUE TITLE
Update outdated hyperlinks in comments

### ISSUE THREAD

**Issue by wofsauge** [manaphoenix/IsaacTemplates#33]
In the character template and possibly other locations there are hyperlinks to different pages of the community documentation. So.e of these links, like shown on the image are broken because they use an outdated format. Those links should be  updated with the new format like this:
https://wofsauge.github.io/IsaacDocs/rep/xml/costumes2.html

https://media.discordapp.net/attachments/993979509328056381/993983765447725066/unknown.png

**Comment by manaphoenix** [comment]
Thanks for the report, this has been fixed!
