### ISSUE TITLE
Pocket active items?

### ISSUE THREAD

**Issue by AgentYgh** [manaphoenix/IsaacTemplates#37]
How do I give my custom character a pocket active item instead of just a regular one?

**Comment by AgentYgh** [comment]
And also how do I add gulped trinkets?

**Comment by manaphoenix** [comment]
🤔 I believe neither of these things are features in character template; if you would like character template to have an innate ability to do this without needing to code it yourself; please open separate issues as a suggestion! Thanks.

**Comment by AgentYgh** [comment]
Can I just change the title?
