### ISSUE TITLE
Most images showing up as a black box even when my images are pngs.

### ISSUE THREAD

**Issue by TheLemon27** [manaphoenix/IsaacTemplates#41]
I followed the tutorial to a T and most of the images show up as either nothing or a black box.

List of things that don't show up/are a black box:
- Character select screen sprite (doesn't show) (only the character sprite, the name shows up fine)
- VS screen name (can't tell bcs of black background) (once again, only the name, the portrait shows up fine)
- Death portrait (black box)
- Character costume and/or sprites (black box) (I think it's both, but im unsure)
- Coop Icons (black box)

I've attached a zip file of my character below, hope you can answer this asap!

[Steve The Dull.zip](https://github.com/manaphoenix/IsaacTemplates/files/11519691/Steve.The.Dull.zip)

**Comment by manaphoenix** [comment]
![image](https://github.com/manaphoenix/IsaacTemplates/assets/7843805/5ecfdd67-f9c1-4873-aaef-ee2da159eb1e)
hey hey, this is really simple, this is because your pngs are being saved as 8bit instead of 32bit which is what the game uses!

**Comment by TheLemon27** [comment]
i used paint.net for making my images and i don't think there is a way in it for me to save images as 32bit specifically, (or if there is, i havent found it), do you know of any software i could use to make them 32bit?

**Comment by manaphoenix** [comment]
![image](https://github.com/manaphoenix/IsaacTemplates/assets/7843805/d3359ee4-c16c-46e4-8407-b33db86d0dea)
when hitting "Save As..." I get the choice to use 32bit.

**Comment by TheLemon27** [comment]
ah, ive gotten so used to just clicking past that menu that ive never considered it lol, thanks!
(leaving issue open in case something goes wrong)

**Comment by TheLemon27** [comment]
ok 3 problems ive noticed after fixing the issue

1. Still no portrait in character select
2. the costume doesnt appear
3. the death portrait text is slightly cropped

**Comment by manaphoenix** [comment]
looking at your mod, besides being outdated (like the other issue said)
you skipped a step where you didn't edit your .anm2 files to match your changes.
this is why its not showing up.

**Comment by TheLemon27** [comment]
ok, i got it working now, but i have some criticisms about your tutorial

- i didnt know i was supposed to change  characterportraits.anm2 because the thing that told me to do so was a single sentence with no colors or anything, so i guess my brain just kinda skipped over it. maybe you could make  characterportraits.anm2 and  characterportraitsalt.anm2 blue like the other filenames
- (i had another criticism regarding the animation editor section but on closer inspection what i thought was missing was there in plain sight so that ones on me lol)

(i hope this didnt come off as hostile! i really appreciate your help!)
