### ISSUE TITLE
stats.lua dont do nothin

### ISSUE THREAD

**Issue by krzys9isme** [manaphoenix/IsaacTemplates#46]
so, i followed everything that was said in the "stats.lua" text file but when i save it and boot up isaac my character dosnt have changed stats or items/trinkets. here is how it looks like:

local CharacterBuilder = include("lib.CharacterTemplateLib")

-- first we make a new character
local alpha = CharacterBuilder.newCharacterSet("Alpha")
--[[
	When calling newCharacter you can pass in the characters name to set that
	you can also pass in false if this character does not have a tainted variant

	if your tainted character has a different name you will need to set it afterwards
	by doing:
	
	Alpha.tainted.name = "" -- name here

	however, the base game gives the tainted and regular variant of a character the same name in the code
	so if you want to be like the game, it should be the same.
]]

-- next we setup all the characters stuff:
-- Note: anything you don't want you don't need to put, just remove it

--[[
	To add a costume you do
	Character:AddCostume(ID)
	
	you can do this multiple times if you have multiple costumes.

	If your character does not have a costume you can remove this line

	NOTE: your anm2 must be in ".\resources\gfx\characters" or it will not be found.
]]

alpha:addItem(CollectibleType.COLLECTIBLE_AQUARIUS, true) 
--[[
  For every item you want to add to your character repeat this line.
  character:AddItem(ItemID, RemoveCostume)
  
  ItemID is the item ID you want to add, you can use the CollectibleType Enum to make this easier (like shown in the example)
  
  RemoveCostume is if you want to remove that items' costume.
  Put true if you want to remove it.
  Put false or just don't include it if you want to keep the costume.
  
  If you do not want to add any items to this character, just remove all of these lines.
	  
  You can find a list of avaliable CollectibleType's here: https://wofsauge.github.io/IsaacDocs/rep/enums/CollectibleType.html
]]

alpha:setTrinket(TrinketType.TRINKET_STEM_CELL)
--[[
	Use the above line to give the character a starting trinket.
	If you do not want a starting trinket, just remove this line

	You can find a list of avaliable TrinketType's here: https://wofsauge.github.io/IsaacDocs/rep/enums/TrinketType.html
]]

--[[
	Use the above line to give the character a starting PocketItem.
	
	It can be either a card like above
	or a pill

	if you want a pill you need to do
	SetPocketItem(CardID, true) -- true means that your telling the template that this is a pill not a card.

	if you do not want a starting PocketItem you can just remove this line.

	You can find a list of avaliable Cards here: https://wofsauge.github.io/IsaacDocs/rep/enums/Card.html
	You can find a list of avaliable PillEffect's here: https://wofsauge.github.io/IsaacDocs/rep/enums/PillEffect.html

	NOTE: Exclusive, you cannot give both a Card and a Pill
]]

--[[
	Use the above line to give your starting active item a default charge
	if you have no active item, or you want no charges, you can just remove this line.
	set to a number for specific charges
	set to true for full charge :)
]]

-- next we need to setup our players stats
local normalStats = CharacterBuilder.newStatTable() -- create a new stat table
normalStats.Damage = 5.50
normalStats.Firedelay = 3.73
normalStats.Shotspeed = 2.00
normalStats.Range = 7.50
normalStats.Speed = 2.00
normalStats.Tearflags = TearFlags.TEAR_POISON | TearFlags.TEAR_FREEZE
normalStats.Tearcolor = Color(1.0, 1.0, 1.0, 1.0, 0, 0, 0) -- Color, first four arguments between 0 and 1
normalStats.Flying = false
normalStats.Luck = 1.00

normalStats.criticalChance = 0
normalStats.criticalMultiplier = 2
--[[
	These two stats are for if the user is Running the Critical Hit Lib

	Critical Chance is how often you can crit, it is a value between 0 and 1
	Defaults to 0
	Critical Multiplier is how much your damage is multiplied by, it is a value between 0.01 - inf
	(Yes, this means your critical multiplier can actually reduce your damage)
	Defaults to 2x

	if you do not set these stats and they are running your character will simply start with no critchance and 2x crit multiplier
]]

alpha:setStats(normalStats)

--[[
	Replace these stats with the values you want, make sure you use the correct type.

	These stats override the base stats (see below), which are based on Isaac,
	
	You only need to include the stats you want to change, if you don't want them, just remove the line

	Base Stats:
	Speed: 1.15
	Firedelay: 2.50
	Damage: 3.00
	Range: 7.50
	Shotspeed: 1.15
	Luck: 1.00
	Tearflags: none
	Flying: false
	Tearcolor: none (defaults to white, so there is no reason to set this)

	Tear Flags:
	For multiple tear effects, you must seperate each tear flag using the '|' (bitwise or) symbol.
	You can find a list of TearFlags here: https://wofsauge.github.io/IsaacDocs/rep/enums/TearFlags.html
]]

--[[
	TAINTED CHARACTER SETUP

	Now do it all again for your tainted character :)
]]
alpha:setTrinket(TrinketType.TRINKET_STEM_CELL, true)
-- its just like above, except we add a "true" onto the end to tell the template that this is the tainted variant were talking about

alpha:addItem(CollectibleType.COLLECTIBLE_AQUARIUS, true, true) -- I want Sad Onion and give me the costume.
-- again just like above, except we need to add true as the third option to let the template know were talking about the tainted variant

 -- this is a pill, so the second option is true, and third option tells the template its the tainted variant
-- even if this is a card you would need the third option
-- so it would look like "Alpha:SetPocketItem(CardType, false, true)" meaning, its a card so set the second one to false, and third tells the template its the tainted variant

local taintedStats = CharacterBuilder.newStatTable() -- create a new stat table
taintedStats.Damage = 3.50
taintedStats.Firedelay = 3.00
taintedStats.Shotspeed = 1.50
taintedStats.Range = 7.50
taintedStats.Speed = 1.30
taintedStats.Tearflags = none
taintedStats.Tearcolor = Color(1.0, 1.0, 1.0, 1.0, 0, 0, 0) -- Color, first four arguments between 0 and 1
taintedStats.Flying = false
taintedStats.Luck = 1.00

alpha:setStats(taintedStats, true) -- true again at the end, getting the idea now?

--[[
	--MORE INFO:--
	
	--Tear Color Info:--
	for tearcolor the first 4 numbers are the color of the base tear, and the last 3 numbers are for the "overlay" tear color
	default value is (1,1,1,1,0,0,0)

	color is R,G,B,A,R0,G0,B0
	Red
	Green
	Blue
	Alpha (Transparency)
	Red offset
	Green offset
	Blue Offset

	The first four numbers are normalized between 0 and 1, basically to get a normalized RGB value take the RGB value from 0-255 and divide by 255. thats the normalized number.
	
	Offset values are input directly as 0-255 instead of being normalized.
	
	--Item Info:--
	For vanilla items, here are links to vanilla Enumerators:
	Vanilla Items: https://wofsauge.github.io/IsaacDocs/rep/enums/CollectibleType.html
	Trinkets: https://wofsauge.github.io/IsaacDocs/rep/enums/TrinketType.html
	Cards: https://wofsauge.github.io/IsaacDocs/rep/enums/Card.html
	Pills: https://wofsauge.github.io/IsaacDocs/rep/enums/PillColor.html

	For modded items, use these functions instead:
	Isaac.GetItemIdByName("CUSTOMITEM")
	Isaac.GetPillEffectByName("CUSTOMPILL")
	Isaac.GetCardIdByName("cardHudName")
	Isaac.GetTrinketIdByName("trinketName")
	Make sure to use the same name as in the items.xml file.
]]

return CharacterBuilder.build() -- last thing we call to tell the character builder were done.

If someone knows whats wrong please help!

**Comment by TheLemon27** [comment]
did you rename your character in players.xml? if you did, then that's the problem. just replace this line: `local alpha = CharacterBuilder.newCharacterSet("Alpha")` with this one: `local alpha = CharacterBuilder.newCharacterSet("YOURNAMEHERE")` (replace YOURNAMEHERE with the name of your character).

if it still doesn't work after that then you're using an outdated template. in that case; simply download the latest version and you should be set

Hope this helps! :3

**Comment by krzys9isme** [comment]
whenever i renamed the character as you said the character wont even show up in the game but whenever i rename it back to "Alpha" it shows back up

> did you rename your character in players.xml?

if you mean the <player...name=... and so on    then yes i did rename it and if thats the problem then what should i rename it back to?

**Comment by TheLemon27** [comment]
do you mean "won't show up" as in invisible, or as in not even on the character select screen

If you mean the latter, go to content>gfx and open the file charactermenu.anm2. if it says "Alpha" on the left side then click it and rename it to your character's name (image below for clarity).
![isaac mod screenshodt](https://github.com/manaphoenix/IsaacTemplates/assets/44980845/75469b04-db62-48ab-a792-ee5416cd8261)
while youre at it, you should also check your other .anm2 files in the mod and replace any "Alpha"'s with your characters name (it's in the same spot)

if you mean the former, (or you tried the above solution and your character is invisible anyway), this is probably because your image files don't have 32-bit depth. this is a simple fix, just go into your image editing program and save/export the image with 32-bit depth. (the exact steps depend on what image editing software you use)

**Comment by manaphoenix** [comment]
didn't get an email for this issue, bad Github! But, thanks for helping out there lemon :)

**Comment by krzys9isme** [comment]
> If you mean the latter, go to content>gfx and open the file charactermenu.anm2. if it says "Alpha" on the left side then click it and rename it to your character's name 

whenever i go into the .anm2 files there is no "Alpha" or my characters name there is only "animation" and when i downloaded a copy of the template and grabbed the .anm2 file from there and edited it then i cant get it to save and when i enter the game the "Alpha" that i changed to my character's name isnt there anymore

I also know that there is a certain sprite bug that happened when i replaced the charactermenu.png file with a edited one, mainly the sprites in game are off center and in the non-tainted version of the character the name isnt even there

**Comment by krzys9isme** [comment]
> do you mean "won't show up" as in invisible, or as in not even on the character select screen

Not on the character select screen

> If you mean the latter, go to content>gfx and open the file charactermenu.anm2. if it says "Alpha" on the left side then click it and rename it to your character's name
while youre at it, you should also check your other .anm2 files in the mod and replace any "Alpha"'s with your characters name 

Already did that

> if you mean the former, (or you tried the above solution and your character is invisible anyway), this is probably because your image files don't have 32-bit depth. this is a simple fix, just go into your image editing program and save/export the image with 32-bit depth. (the exact steps depend on what image editing software you use)

could you recomend any programs that work? because it may be the programs that i use fault

**Comment by manaphoenix** [comment]
what image editing software do you use?

**Comment by krzys9isme** [comment]
i used aseprite

**Comment by manaphoenix** [comment]
hmm, aseprite I think natively uses 32 bit (8bpp) ... if you can upload your mod I'll take a closer at it tho.

**Comment by krzys9isme** [comment]
here it is, if there is anything missing please let me know!
also the mod might be labeled as: "tymczasowe" in game

**Comment by manaphoenix** [comment]
Alright, so your stats.lua is just plain wrong, idk what you did but id suggest redownloading the file b/c its *VERY* wrong.

**Comment by manaphoenix** [comment]
top image is your file, bottom is the default file and what it should look like (but ofc with ur items)
![image](https://github.com/manaphoenix/IsaacTemplates/assets/7843805/d63a3ba5-d235-4ebe-b12c-686b49944fa0)
![image](https://github.com/manaphoenix/IsaacTemplates/assets/7843805/a43ef3dc-59a2-47c3-906d-6a7f99eade09)

**Comment by krzys9isme** [comment]
well i downloaded the newest version of the template just in case and i changed and the double checked if anything is wrong but it still dosnt work, im sorry if im being a bother but im bad at coding
anyways here is the file:

i changed the file type from lua to txt of course

**Comment by manaphoenix** [comment]
are you using an actual editor for coding? it would help you figure out what you're doing wrong. this stats.lua is still very much incorrect.

**Comment by krzys9isme** [comment]
i meant coding as in i dont know what im doing thats why im making so many mistakes whith the stats.lua, because i dont know whats esential and whats not

**Comment by manaphoenix** [comment]
I understand but you didn't actually answer the question: if you're not get VSCode, it even has an addon to help specifically with Isaac Modding.

**Comment by krzys9isme** [comment]
i dont understand what you mean if your saying that there is a fix in VSCode then what is the name of the extention?
but i didnt code anything myself btw. i just want to do the stats and items

**Comment by manaphoenix** [comment]
![image](https://github.com/manaphoenix/IsaacTemplates/assets/7843805/c4380eb9-8d97-40d2-8e0c-4966e4b69168)
this is the extension :)

and its not a "fix" it won't do it for you, you're going to have spend a little bit of time to understand what's going on.

**Comment by krzys9isme** [comment]
well i fixed it, thanks for the help!

**Comment by Blockido** [comment]
How did you fix it?
