### ISSUE TITLE
diffrent skincolors

### ISSUE THREAD

**Issue by krzys9isme** [manaphoenix/IsaacTemplates#47]
hey so in players.xml you can choose what skincolour your guy will have but im wondering, can you set it too diffrent things? Because whenever i pickup a item like for example spoon bender with my character the head changes colour to what isaac's would be and i would like it to be just my guys head, so is there any current solution to this?

**Comment by manaphoenix** [comment]
Sorry I don't know much about the costume system. I would suggest joining the Modding Discord, or the Isaac Discord. They have people there that could answer quite fast for you.
