### ISSUE TITLE
Chaos not working all the time for starting items in main.lua

### ISSUE THREAD

**Issue by ThatOneVultra** [manaphoenix/IsaacTemplates#9]
I don't know _why_ but adding Chaos to the custom character seems to crash the game
Only sometimes too, half the time I can load the character fine but if I hold R enough times it crashes

I've tested with only changing the item on a fresh template and I've managed to replicate it too just giving the characters chaos (item 402). For both the default and tainted versions, so I don't think I have to send anything. Don't want the costume so I can't just use players.xml sadly.

At the very least I know for a fact it's Chaos causing it, I didn't change anything in the entire mod template apart from adding the item.

![image](https://user-images.githubusercontent.com/84760950/119802691-ad050c00-bed6-11eb-8187-1b3cb2fe93b0.png)

**Comment by manaphoenix** [comment]
hey one question, did you allow chaos to add its costume (if it has one?)

**Comment by ThatOneVultra** [comment]
> hey one question, did you allow chaos to add its costume (if it has one?)

thanks for responding!

I've tested a lot with the costume disabled mainly but I've tested it again with the costume enabled and disabled
and both times the issue was still there (_Only most of the time too, there's been times where the character starts fine but restarting gets the crash eventually_)

The first time I crashed I thought it was something i messed up but it's still there on a fresh template too

**Comment by manaphoenix** [comment]
I believe this has being fixed. Open a new issue if not!
